/** Responsive homepage styles; no external fonts or asset requests. */
export const styles = `
:root{font-family:Inter,ui-sans-serif,system-ui,-apple-system,"Segoe UI",sans-serif;color:#202b27;background:#f7f8f4;font-synthesis:none;line-height:1.6;scroll-behavior:smooth}
*{box-sizing:border-box}body{margin:0}a{color:inherit;text-decoration:none}a:focus-visible{outline:3px solid #42634d;outline-offset:6px;border-radius:4px}
.wrap{width:min(1120px,calc(100% - 64px));margin:auto}header{height:100px;display:flex;align-items:center;justify-content:space-between;border-bottom:1px solid #dce1d7}.brand{display:flex;gap:12px;align-items:center;font-size:22px;font-weight:700;letter-spacing:-1px}.mark{display:grid;place-items:center;width:36px;height:36px;background:#274d3e;color:white;border-radius:11px;font-size:22px;letter-spacing:-4px;padding-right:4px}nav{display:flex;align-items:center;gap:32px;font-size:14px}.language{border:1px solid #cbd3c8;padding:6px 14px;border-radius:30px}
.hero{position:relative;padding:106px 0 98px;max-width:870px}.eyebrow{font-size:12px;font-weight:650;letter-spacing:2px;color:#52705d;display:flex;align-items:center;gap:10px}.dot{width:7px;height:7px;border-radius:50%;background:#668570}h1{text-wrap:balance;font-size:clamp(42px,6vw,76px);line-height:1.22;letter-spacing:-3px;margin:28px 0;max-width:820px;font-weight:550}.description{max-width:610px;font-size:18px;color:#69746d;line-height:1.9}.actions{display:flex;align-items:center;gap:28px;margin-top:38px;font-size:14px}.primary{display:inline-flex;gap:30px;align-items:center;background:#274d3e;color:#fff;padding:14px 22px;border-radius:8px}.primary:hover{background:#36634f}.secondary{border-bottom:1px solid #a6b4a5;padding:8px 0}.section{padding:54px 0 74px;border-top:1px solid #dce1d7;scroll-margin-top:24px}.label{font-size:12px;letter-spacing:2px;color:#6d7f6a}h2{font-size:30px;font-weight:500;letter-spacing:-1px;margin:14px 0 32px}.cards{display:grid;grid-template-columns:repeat(3,1fr);gap:18px}.card{background:#fff;border:1px solid #e2e7df;border-radius:14px;padding:30px}.number{font-family:ui-monospace,monospace;font-size:12px;color:#728574}h3{font-size:18px;font-weight:550;margin:26px 0 12px}.card p{font-size:14px;color:#727b73;margin:0}.about{display:flex;gap:60px;justify-content:space-between;align-items:start}.about h2{max-width:440px;margin-top:0}.about p{max-width:440px;color:#69746d;margin:0}footer{padding:28px 0 38px;border-top:1px solid #dce1d7;display:flex;justify-content:space-between;color:#778175;font-size:12px}
@media(max-width:640px){.wrap{width:calc(100% - 40px)}header{height:80px}.brand{font-size:19px}nav{gap:16px}nav .home-link{display:none}.hero{padding:70px 0}h1{letter-spacing:-1.5px}.description{font-size:16px}.actions{gap:20px}.cards{grid-template-columns:1fr}.card{padding:25px}.about{display:block}.about p{margin-top:22px}h2{font-size:26px}footer{gap:20px}.section{padding:40px 0 50px}}
@media(prefers-reduced-motion:reduce){:root{scroll-behavior:auto}}
`
